Tienda/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('apps.Tienda.urls')),
    path('tienda/',include('apps.Tienda.urls')),
]

apps/Tienda/urls.py
from django.urls import path
from apps.Tienda.views import index,categorias
from apps.Tienda.views import modificarProducto
from apps.Tienda.views import nuevoProducto
from apps.Tienda.views import eliminarProducto
from apps.Tienda.views import ProductoListView
from apps.Tienda.views import nuevaCategoria
from apps.Tienda.views import modificarCategoria
from apps.Tienda.views import eliminarCategoria
from apps.Tienda.views import ventas
from apps.Tienda.views import resumenVentas
from apps.Tienda.views import ventasBsq

app_name='tienda'
urlpatterns = [
   path('categorias',categorias,name="cat"),
   path('',index,name="index"),
   path('productos',ProductoListView.as_view(),name="prd"),
   path('nuevoProducto',nuevoProducto,name="nuevoPrd"),
   path('modProducto/<idProducto>',modificarProducto,name="modPrd"),
   path('eliminarProducto/<idProducto>',eliminarProducto,name="rmvPrd"),
   path('nuevaCategoria',nuevaCategoria,name="nuevaCat"),
   path('modCategoria/<idCategoria>',modificarCategoria,name="modCat"),
   path('rmvCategoria/<idCategoria>',eliminarCategoria,name="rmvCat"),
   path('ventas',ventas,name="ventas"),
   path('resumen/<idProducto>',resumenVentas,name="resumen"),
   path('busqueda',ventasBsq,name="ventasBsq"),
]

templates/base/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible">
    <title>{% block title %}Proyecto{% endblock %}</title>
    {% comment %} Favicon {% endcomment %}
    <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}" type="image/x-icon">
    <link rel="icon" href="{% static 'img/favicon.ico' %}" type="image/x-icon">
    <!--Hoja de estilos principal-->
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <!--Bloque para estilos diferentes posteriores-->
    {% block extracss %}
    {% endblock extracss %}
    <script type="text/javascript" src="{% static 'js/main.js' %}"></script>
</head>

<body>
    <header>
        {% block header %}
        <div>
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <a class="navbar-brand" href="{% url 'tienda:index' %}">Proyecto Tienda</a>
                 <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor03" aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            <div class="collapse navbar-collapse" id="navbarColor03">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item active">
                            <a class="nav-link" href="{% url 'tienda:index' %}">Inicio<span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'tienda:prd' %}">Productos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'tienda:cat' %}">Categorías</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'tienda:ventas' %}">Ventas</a>
                        </li>
                    </ul>
                </div>
            </nav>
        </div>
        {% endblock %}
    </header>
    <br>
    <div class="container">
        {% block content %}
        <p>
            Proyecto Final Taller Django 
        </p>
        <p>
            Samuel Toral Pacheco 239895
        </p>
        
        {% endblock %}</div>
    <br>
    <footer class="container blockquote-footer">{% block footer %}Taller Django{% endblock %}</footer>

</body>

</html>