Tienda/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('apps.Tienda.urls')),
    path('tienda/',include('apps.Tienda.urls')),
]

apps/Tienda/urls.py
from django.urls import path
from apps.Tienda.views import index,categorias
from apps.Tienda.views import modificarProducto
from apps.Tienda.views import nuevoProducto
from apps.Tienda.views import eliminarProducto
from apps.Tienda.views import ProductoListView
from apps.Tienda.views import nuevaCategoria
from apps.Tienda.views import modificarCategoria
from apps.Tienda.views import eliminarCategoria
from apps.Tienda.views import ventas
from apps.Tienda.views import resumenVentas
from apps.Tienda.views import ventasBsq

app_name='tienda'
urlpatterns = [
   path('categorias',categorias,name="cat"),
   path('',index,name="index"),
   path('productos',ProductoListView.as_view(),name="prd"),
   path('nuevoProducto',nuevoProducto,name="nuevoPrd"),
   path('modProducto/<idProducto>',modificarProducto,name="modPrd"),
   path('eliminarProducto/<idProducto>',eliminarProducto,name="rmvPrd"),
   path('nuevaCategoria',nuevaCategoria,name="nuevaCat"),
   path('modCategoria/<idCategoria>',modificarCategoria,name="modCat"),
   path('rmvCategoria/<idCategoria>',eliminarCategoria,name="rmvCat"),
   path('ventas',ventas,name="ventas"),
   path('resumen/<idProducto>',resumenVentas,name="resumen"),
   path('busqueda',ventasBsq,name="ventasBsq"),
]

apps/Tienda/models.py
from django.db import models
# Create your models here.


class Categoria(models.Model):
    nombre = models.CharField(max_length=30)
    fechaCreacion=models.DateField(default='2000-01-01')


class Producto(models.Model):
    categoria = models.ForeignKey(
        Categoria, null=True, blank=True, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=30)
    descripcion = models.CharField(max_length=75)
    costo = models.DecimalField(decimal_places=2, max_digits=15)
    disponible = models.BooleanField()
    numExistencias = models.IntegerField()

class Ventas(models.Model):
    # producto=models.ForeignKey(
    #     Producto,blank=True, null=True,on_delete=models.CASCADE)
    producto=models.CharField(max_length=75,default=" ")
    precio=models.DecimalField(decimal_places=2,max_digits=15,default=0)
    cantidad=models.IntegerField(default=0)
    total=models.DecimalField(decimal_places=2,max_digits=15,default=0)



apps/Tienda/forms.py
from django import forms
from apps.Tienda.models import Producto
from apps.Tienda.models import Categoria
from apps.Tienda.models import Ventas

# Genera una Venta


class Venta(forms.ModelForm):
    class Meta:
        model = Ventas
        # exclude=('producto','precio','total')

        fields = [
            'producto',
            'precio',
            'cantidad',
            'total'
        ]

        labels = {
            'producto': 'Producto',
            'precio':'Precio',
            'cantidad': 'Cantidad',
            'total': 'Total'
        }

        widgets = {
            'producto': forms.TextInput(attrs={'class': 'form-control','readonly':''}),
            'precio':forms.NumberInput(attrs={'class': 'form-control','readonly':''}),
            'cantidad': forms.NumberInput(attrs={'class': 'form-control','onchange':'subtotal()','min':'0'}),
            'total': forms.NumberInput(attrs={'class': 'form-control', 'readonly':''}),
        }


# Agrega o modifca un Producto
class ProductoForm(forms.ModelForm):
    class Meta:
        model = Producto

        fields = [
            'nombre',
            'categoria',
            'descripcion',
            'costo',
            'disponible',
            'numExistencias',
        ]

        labels = {
            'nombre': 'Nombre',
            'categoria': 'Categoría',
            'descripcion': 'Descripción',
            'costo': 'Costo',
            'disponible': 'Disponible',
            'numExistencias': 'Número de Existencias',
        }

        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control'}),
            'categoria': forms.TextInput(attrs={'class': 'form-control'}),
            'descripcion': forms.TextInput(attrs={'class': 'form-control'}),
            'costo': forms.TextInput(attrs={'class': 'form-control'}),
            'disponible': forms.CheckboxInput(attrs={'clas': 'form-check-input'}),
            'numExistencias': forms.TextInput(attrs={'class': 'form-control'}),
        }


# Agrega o Modifica una Categoria
class CategoriaForm(forms.ModelForm):
    class Meta:
        model = Categoria

        fields = [
            'nombre',
            'fechaCreacion',
        ]

        labels = {
            'nombre': 'Nombre',
            'fechaCreacion': 'Fecha Creación',
        }

        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control'}),
            'fechaCreacion': forms.DateInput(attrs={'class': 'form-control'}),
        }

apps/Tienda/views.py
from django.shortcuts import render,redirect
from apps.Tienda.models import Categoria
from apps.Tienda.models import Producto
from apps.Tienda.models import Ventas
from django.views.generic import ListView
from apps.Tienda.forms import ProductoForm
from apps.Tienda.forms import CategoriaForm
from apps.Tienda.forms import Venta
from django.contrib import messages
# Create your views here.

def index(request):
    return render(request,'base/index.html')


# Ventas de Productos


def ventas(request):
    context = {'productos': Producto.objects.all()}
    return render(request,'Tienda/ventas.html',context)

def ventasBsq(request):
    nombrePrd=request.GET.get('campo')
    context = {'productos': Producto.objects.filter(nombre=nombrePrd)}
    return render(request,'Tienda/ventasBsq.html',context)


def resumenVentas(request,idProducto):
    producto=Producto.objects.get(id=idProducto)
    total=0*producto.costo
    nombre=producto.nombre+" "+producto.descripcion
    costo=producto.costo
    if request.method=='POST':
        form = Venta(request.POST,initial={'producto':nombre,'cantidad':0,'total':total,'precio':costo})
        if form.is_valid():
            resta=form.cleaned_data['cantidad']
            if(resta>producto.numExistencias):
                messages.error(request," No hay sificiente producto en inventario para esa compra")
                return render(request, 'Tienda/resumenVenta.html',{'form':form})
            else:
                messages.success(request,"Venta exitosa")
                producto.numExistencias=producto.numExistencias-resta
                if(producto.numExistencias==0):
                    producto.disponible=False
                producto.save()
                form.save()
        return redirect('tienda:prd')
    else:
        form = Venta(initial={'producto':nombre,'cantidad':0,'total':total,'precio':costo})
    return render(request, 'Tienda/resumenVenta.html',{'form':form})

#Categorías


def categorias(request):
    context = {'categorias': Categoria.objects.all()}
    return render(request, 'Tienda/cat.html', context)

def nuevaCategoria(request):
    if request.method=='POST':
        form=CategoriaForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect('tienda:cat')
    else:
        form=CategoriaForm()
    return render(request, 'Tienda/FormCat.html',{'form':form})

def modificarCategoria(request,idCategoria):
    categoria=Categoria.objects.get(id=idCategoria)
    if(request.method=="GET"):
        form = CategoriaForm(instance=categoria)
    else:
        form = CategoriaForm(request.POST,instance=categoria)
        if form.is_valid():
            form.save()
        return redirect('tienda:cat')
    return render(request, 'Tienda/FormCat.html',{'form':form})

def eliminarCategoria(request,idCategoria):
    categoria= Categoria.objects.get(id=idCategoria)
    categoria.delete()
    return redirect('tienda:cat')

# Productos

def nuevoProducto(request):
    if request.method=='POST':
        form=ProductoForm(request.POST)
        if form.is_valid():
        form.save()
        return redirect('tienda:prd')
    else:
        form=ProductoForm()
    return render(request, 'Tienda/FormPrd.html',{'form':form})

def modificarProducto(request,idProducto):
    producto=Producto.objects.get(id=idProducto)
    if(request.method=="GET"):
        form = ProductoForm(instance=producto)
    else:
        form = ProductoForm(request.POST,instance=producto)
        if form.is_valid():
            form.save()
        return redirect('tienda:prd')
    return render(request, 'Tienda/FormPrd.html',{'form':form})

def eliminarProducto(request,idProducto):
    producto = Producto.objects.get(id=idProducto)
    producto.delete()
    return redirect('tienda:prd')

class ProductoListView(ListView):
    model = Producto
    queryset=Producto.objects.all()  
    template_name = "Tienda/productos.html"






templates/Tienda/FormCat.html
{% extends 'base/index.html' %}
{% block titles %}
Form Categoría
{% endblock titles %}
{% block content %}
<div class="container-fluid mt-3">
    <div class="row justify-content-center">
        <div class="col-6">
            <h1>Agregar una Nueva Categoría</h1>
            <form method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <button type="submit" class="btn btn-primary">Enviar</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

templates/Tienda/FormPrd.html
{% extends 'base/index.html' %}
{% block title %}
Form Productos
{% endblock title %}
{% block content %}
<div class="container-fluid mt-3">
    <div class="row justify-content-center">
        <div class="col-6">
            <h1>Agregar un Nuevo Producto</h1>
            <form method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <button type="submit" class="btn btn-primary">Enviar</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

templates/Tienda/cat.html
{% extends 'base/index.html' %}

{% block title %}Categorias{% endblock %}

{% block content %}
<h1>Categorías</h1><br>
<div class="container-fluid mt-3">
		<a class="btn mb-3" href="{% url 'tienda:nuevaCat' %}">Nuevo Registro</a><br>
		<table class="table table-borderless">
			<thead class="thead">
				<tr>
					<th scope="col">Id</th>
					<th scope="col">Nombre</th>
					<th scope="col">Fecha de Creación</th>
				</tr>
			</thead>
			<tbody>
				{% for categoria in categorias %}
				<tr>
					<th scope="row">{{categoria.id}}</td>
					<td>{{categoria.nombre}}</td>
					<td>{{categoria.fechaCreacion}}</td>
					<td>
						<a  href="{% url 'tienda:modCat' categoria.id  %}" class="btn btn-primary">Editar</a>
						<a  href="{% url 'tienda:rmvCat' categoria.id  %}" class="btn btn-danger">Eliminar</a>
					</td>
				{% empty %}
					<td span="6">No hay Categorías Registradas</td>
				</tr>
				{% endfor %}
			</tbody>
		</table>
	</div>
{% endblock %}
{% block footer %}
Proyecto Tienda
{% endblock footer %}

templates/Tienda/productos.html
{% extends 'base/index.html' %}

{% block title %}Productos{% endblock %}

{% block content %}
{% if messages %}
            <br>
    {% for message in messages %}
            <div class="alert alert-dismissible  alert-success" id="msg" >
                <button type="button" class="close"  onclick="cerrar()">&times;</button>
                {{ message }}
            </div>
    {% endfor %}
{% endif %}
<h1>Productos</h1><br>
		<a class="btn mb-3" href="{% url 'tienda:nuevoPrd' %}">Nuevo Registro</a><br>
		<table class="table table-borderless">
			<thead class="thead">
				<tr>
					<th scope="col">Id</th>
					<th scope="col">Categoria</th>
					<th scope="col">Nombre</th>
					<th scope="col">Descripción</th>
					<th scope="col">Costo</th>
					<th scope="col">Disponible</th>
					<th scope="col">Número Existencias</th>
					<th scope="col">Acciones</th>
				</tr>
			</thead>
			<tbody>
				{% for producto in object_list %}
				<tr>
					<th scope="row">{{producto.id}}</td>
					<td>{{producto.categoria_id}}</td>
					<td>{{producto.nombre}}</td>
					<td>{{producto.descripcion}}</td>
					<td>{{producto.costo}}</td>
					<td>{{producto.disponible}}</td>
					<td>{{producto.numExistencias}}</td>
				
					<td>
						<a  href="{% url 'tienda:modPrd' producto.id  %}" class="btn btn-primary">Editar</a>
						<a  href="{% url 'tienda:rmvPrd' producto.id  %}" class="btn btn-danger">Eliminar</a>
					</td>
				{% empty %}
					<td span="6">No hay Productos Registrados</td>
				</tr>
				{% endfor %}
			</tbody>
		</table>
{% endblock %}

templates/Tienda/resumenVenta.html
{% extends 'base/index.html' %}
{% load static %}
{% block content %}

<div class="container-fluid mt-3">
    <div class="row justify-content-center">
        <div class="col-6">
         {% if messages %}
                <br>
            {% for message in messages %}
                <div class="alert alert-dismissible alert-danger" id="msg" >
                    <button type="button" class="close"  onclick="cerrar()">&times;</button>
                    {{ message }}
                </div>
            {% endfor %}
            {% endif %}
            <h1>Ventas</h1>
            <form method="POST" >
                {% csrf_token %}
                {{form.as_p}}
                <button type="submit" class="btn btn-primary" id="btn" disabled>Realizar Compra</button>
            </form>
           
        </div>
    </div>
</div>


{% endblock content %}

templates/Tienda/ventas.html
{% extends 'base/index.html' %}
{% block title %}
Venta de Productos
{% endblock title %}
{% block content %}

<h1>Venta de Productos</h1><br>
<div class="container-fluid mt-3">
	<form class="form-inline my-2 my-lg-0 " style="text-aling:left;" action="{% url 'tienda:ventasBsq' %}" method="GET">
		<input class="form-control mr-sm-2" type="text" placeholder="Buscar por Nombre" name="campo">
		<button class="btn btn-secondary my-2 my-sm-0" type="submit">Buscar</button>
	</form>
	
</div><br>
<table class="table table-borderless">
	<thead class="thead">
		<tr>
			<th scope="col">Nombre</th>
			<th scope="col">Descripción</th>
			<th scope="col">Costo</th>
			<th scope="col">Disponible</th>
			<th scope="col">Número Existencias</th>
			<th scope="col">Acciones</th>
		</tr>
	</thead>
	<tbody>
		{% for producto in productos %}
		<tr>
			<td>{{producto.nombre}}</td>
			<td>{{producto.descripcion}}</td>
			<td>{{producto.costo}}</td>
			<td>{{producto.disponible}}</td>
			<td>{{producto.numExistencias}}</td>
			{% if producto.disponible %}
			<td>
				<a href="{% url 'tienda:resumen' producto.id  %}" class="btn btn-success">Comprar</a>
			</td>
			{% else %}
			<td>
				<a href="{% url 'tienda:resumen' producto.id  %}" class="btn btn-danger disabled">Comprar</a>
			</td>
			{% endif %}
			{% empty %}
			<td span="6">No hay Productos Registrados</td>
		</tr>
		{% endfor %}
		
	</tbody>
</table>
{% endblock content %}

templates/Tienda/ventasBsq.html
{% extends 'base/index.html' %}
{% block title %}
Venta de Productos
{% endblock title %}
{% block content %}

<h1>Venta de Productos</h1><br>
<div class="container-fluid mt-3">
	<a href="{% url 'tienda:ventas' %}">Regresar a Lista completa</a>
</div><br>
<table class="table table-borderless">
	<thead class="thead">
		<tr>
			<th scope="col">Nombre</th>
			<th scope="col">Descripción</th>
			<th scope="col">Costo</th>
			<th scope="col">Disponible</th>
			<th scope="col">Número Existencias</th>
			<th scope="col">Acciones</th>
		</tr>
	</thead>
	<tbody>
		{% for producto in productos %}
		<tr>
			<td>{{producto.nombre}}</td>
			<td>{{producto.descripcion}}</td>
			<td>{{producto.costo}}</td>
			<td>{{producto.disponible}}</td>
			<td>{{producto.numExistencias}}</td>
			{% if producto.disponible %}
			<td>
				<a href="{% url 'tienda:resumen' producto.id  %}" class="btn btn-success">Comprar</a>
			</td>
			{% else %}
			<td>
				<a href="{% url 'tienda:resumen' producto.id  %}" class="btn btn-danger disabled">Comprar</a>
			</td>
			{% endif %}
			{% empty %}
			<td span="6">No hay Productos Con ese Nombre</td>
		</tr>
		{% endfor %}
		
	</tbody>
</table>
{% endblock content %}